#pragma once
#include "ast.h"
#include <sstream>
#include <stdexcept>

class CodeGen {
public:
    std::string generate(const NodePtr& root) {
        std::ostringstream out;
        out << "// Generated by MiniC Compiler\n";
        out << "\"use strict\";\n\n";
        genNode(root, out, 0);
        return out.str();
    }

private:
    std::string indent(int level) {
        return std::string(level * 2, ' ');
    }

    void genNode(const NodePtr& node, std::ostringstream& out, int lvl) {
        switch (node->type) {

            case NodeType::Program:
                genNode(node->children[0], out, lvl);
                break;

            case NodeType::StmtList:
                for (auto& child : node->children)
                    genNode(child, out, lvl);
                break;

            case NodeType::VarDecl: {
                // children[0] = identifier, children[1] = expr
                out << indent(lvl) << "let "
                    << node->children[0]->value << " = ";
                genExpr(node->children[1], out);
                out << ";\n";
                break;
            }

            case NodeType::AssignStmt: {
                // children[0] = identifier, children[1] = expr
                out << indent(lvl)
                    << node->children[0]->value << " = ";
                genExpr(node->children[1], out);
                out << ";\n";
                break;
            }

            case NodeType::PrintStmt: {
                out << indent(lvl) << "console.log(";
                genExpr(node->children[0], out);
                out << ");\n";
                break;
            }

            case NodeType::Block: {
                out << indent(lvl) << "{\n";
                genNode(node->children[0], out, lvl + 1);
                out << indent(lvl) << "}\n";
                break;
            }

            default:
                // Expression used as a standalone statement
                genExpr(node, out);
                out << ";\n";
                break;
        }
    }

    void genExpr(const NodePtr& node, std::ostringstream& out) {
        switch (node->type) {

            case NodeType::IntLit:
            case NodeType::FloatLit:
                out << node->value;
                break;

            case NodeType::BoolLit:
                out << node->value;   // "true" / "false" same in JS
                break;

            case NodeType::Identifier:
                out << node->value;
                break;

            case NodeType::UnaryExpr:
                out << node->value << "(";
                genExpr(node->children[0], out);
                out << ")";
                break;

            case NodeType::BinaryExpr:
                out << "(";
                genExpr(node->children[0], out);
                out << " " << node->value << " ";
                genExpr(node->children[1], out);
                out << ")";
                break;

            default:
                throw std::runtime_error("CodeGen: unexpected node in expression");
        }
    }
};
